version: 2.1

import:
  - .circleci/base_config/parameters.yml
    
jobs:
  semgrep-scan:
    docker:
      - image: semgrep/semgrep
    parameters:
      service:
        type: string
      master_branch:
        type: string
    steps:
      - checkout
      - run:
          name: Set script permissions
          command: chmod +x .circleci/base_config/semgrep.sh
      - run:
          name: "Semgrep scan"
          command: |
              export SERVICE_PARAM=<< parameters.service >>
              .circleci/base_config/semgrep.sh

workflows:
  semgrep:
    jobs:
      - semgrep-scan:
          name: semgrep-scan
          service: "B"
          master_branch: "development"
          context:
            - semgrep
